package com.smartmonkey.mapper;

import com.smartmonkey.model.PartCategory;
import java.util.List;

public interface PartCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int insert(PartCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    PartCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    List<PartCategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PartCategory row);
}