package com.smartmonkey.mapper;

import com.smartmonkey.model.PartCategory;
import com.smartmonkey.model.PartCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    long countByExample(PartCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int deleteByExample(PartCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int insert(PartCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int insertSelective(PartCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    List<PartCategory> selectByExample(PartCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    PartCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PartCategory row, @Param("example") PartCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PartCategory row, @Param("example") PartCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PartCategory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table part_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PartCategory row);
}