package com.smartmonkey.mapper;

import com.smartmonkey.model.SparePart;
import com.smartmonkey.model.SparePartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SparePartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    long countByExample(SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int deleteByExample(SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long partId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int insert(SparePart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int insertSelective(SparePart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    List<SparePart> selectByExampleWithBLOBs(SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    List<SparePart> selectByExample(SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    SparePart selectByPrimaryKey(Long partId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SparePart row, @Param("example") SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") SparePart row, @Param("example") SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SparePart row, @Param("example") SparePartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SparePart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SparePart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SparePart row);
}