package com.smartmonkey.mapper;

import com.smartmonkey.model.SparePart;
import java.util.List;

public interface SparePartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long partId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int insert(SparePart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    SparePart selectByPrimaryKey(Long partId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    List<SparePart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spare_parts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SparePart row);
}