package com.smartmonkey.mapper;

import com.smartmonkey.model.StockOut;
import java.util.List;

public interface StockOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long outId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int insert(StockOut row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    StockOut selectByPrimaryKey(Long outId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    List<StockOut> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockOut row);
}