package com.smartmonkey.mapper;

import com.smartmonkey.model.StockOut;
import com.smartmonkey.model.StockOutExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    long countByExample(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int deleteByExample(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long outId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int insert(StockOut row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int insertSelective(StockOut row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    List<StockOut> selectByExampleWithBLOBs(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    List<StockOut> selectByExample(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    StockOut selectByPrimaryKey(Long outId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StockOut row, @Param("example") StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") StockOut row, @Param("example") StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StockOut row, @Param("example") StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockOut row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StockOut row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockOut row);
}