package com.smartmonkey.mapper;

import com.smartmonkey.model.StockIn;
import java.util.List;

public interface StockInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long inId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int insert(StockIn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    StockIn selectByPrimaryKey(Long inId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    List<StockIn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockIn row);
}