package com.smartmonkey.mapper;

import com.smartmonkey.model.StockIn;
import com.smartmonkey.model.StockInExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    long countByExample(StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int deleteByExample(StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long inId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int insert(StockIn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int insertSelective(StockIn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    List<StockIn> selectByExampleWithBLOBs(StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    List<StockIn> selectByExample(StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    StockIn selectByPrimaryKey(Long inId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") StockIn row, @Param("example") StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") StockIn row, @Param("example") StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") StockIn row, @Param("example") StockInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockIn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(StockIn row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockIn row);
}