package com.smartmonkey.model;

import java.util.Date;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inventory_id
     *
     * @mbg.generated
     */
    private Long inventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.part_id
     *
     * @mbg.generated
     */
    private Long partId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.warehouse
     *
     * @mbg.generated
     */
    private String warehouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.total_quantity
     *
     * @mbg.generated
     */
    private Integer totalQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.available_quantity
     *
     * @mbg.generated
     */
    private Integer availableQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.locked_quantity
     *
     * @mbg.generated
     */
    private Integer lockedQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.last_in_date
     *
     * @mbg.generated
     */
    private Date lastInDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.last_out_date
     *
     * @mbg.generated
     */
    private Date lastOutDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.stock_status
     *
     * @mbg.generated
     */
    private Byte stockStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inventory_id
     *
     * @return the value of inventory.inventory_id
     *
     * @mbg.generated
     */
    public Long getInventoryId() {
        return inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inventory_id
     *
     * @param inventoryId the value for inventory.inventory_id
     *
     * @mbg.generated
     */
    public void setInventoryId(Long inventoryId) {
        this.inventoryId = inventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.part_id
     *
     * @return the value of inventory.part_id
     *
     * @mbg.generated
     */
    public Long getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.part_id
     *
     * @param partId the value for inventory.part_id
     *
     * @mbg.generated
     */
    public void setPartId(Long partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.warehouse
     *
     * @return the value of inventory.warehouse
     *
     * @mbg.generated
     */
    public String getWarehouse() {
        return warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.warehouse
     *
     * @param warehouse the value for inventory.warehouse
     *
     * @mbg.generated
     */
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.total_quantity
     *
     * @return the value of inventory.total_quantity
     *
     * @mbg.generated
     */
    public Integer getTotalQuantity() {
        return totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.total_quantity
     *
     * @param totalQuantity the value for inventory.total_quantity
     *
     * @mbg.generated
     */
    public void setTotalQuantity(Integer totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.available_quantity
     *
     * @return the value of inventory.available_quantity
     *
     * @mbg.generated
     */
    public Integer getAvailableQuantity() {
        return availableQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.available_quantity
     *
     * @param availableQuantity the value for inventory.available_quantity
     *
     * @mbg.generated
     */
    public void setAvailableQuantity(Integer availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.locked_quantity
     *
     * @return the value of inventory.locked_quantity
     *
     * @mbg.generated
     */
    public Integer getLockedQuantity() {
        return lockedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.locked_quantity
     *
     * @param lockedQuantity the value for inventory.locked_quantity
     *
     * @mbg.generated
     */
    public void setLockedQuantity(Integer lockedQuantity) {
        this.lockedQuantity = lockedQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.last_in_date
     *
     * @return the value of inventory.last_in_date
     *
     * @mbg.generated
     */
    public Date getLastInDate() {
        return lastInDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.last_in_date
     *
     * @param lastInDate the value for inventory.last_in_date
     *
     * @mbg.generated
     */
    public void setLastInDate(Date lastInDate) {
        this.lastInDate = lastInDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.last_out_date
     *
     * @return the value of inventory.last_out_date
     *
     * @mbg.generated
     */
    public Date getLastOutDate() {
        return lastOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.last_out_date
     *
     * @param lastOutDate the value for inventory.last_out_date
     *
     * @mbg.generated
     */
    public void setLastOutDate(Date lastOutDate) {
        this.lastOutDate = lastOutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.stock_status
     *
     * @return the value of inventory.stock_status
     *
     * @mbg.generated
     */
    public Byte getStockStatus() {
        return stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.stock_status
     *
     * @param stockStatus the value for inventory.stock_status
     *
     * @mbg.generated
     */
    public void setStockStatus(Byte stockStatus) {
        this.stockStatus = stockStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.created_time
     *
     * @return the value of inventory.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.created_time
     *
     * @param createdTime the value for inventory.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.updated_time
     *
     * @return the value of inventory.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.updated_time
     *
     * @param updatedTime the value for inventory.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}