package com.smartmonkey.model;

import java.math.BigDecimal;
import java.util.Date;

public class SparePart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.part_id
     *
     * @mbg.generated
     */
    private Long partId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.part_no
     *
     * @mbg.generated
     */
    private String partNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.part_name
     *
     * @mbg.generated
     */
    private String partName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.brand
     *
     * @mbg.generated
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.cost_price
     *
     * @mbg.generated
     */
    private BigDecimal costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.sale_price
     *
     * @mbg.generated
     */
    private BigDecimal salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.safety_stock
     *
     * @mbg.generated
     */
    private Integer safetyStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.max_stock
     *
     * @mbg.generated
     */
    private Integer maxStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.supplier
     *
     * @mbg.generated
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.is_active
     *
     * @mbg.generated
     */
    private Byte isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spare_parts.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.part_id
     *
     * @return the value of spare_parts.part_id
     *
     * @mbg.generated
     */
    public Long getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.part_id
     *
     * @param partId the value for spare_parts.part_id
     *
     * @mbg.generated
     */
    public void setPartId(Long partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.part_no
     *
     * @return the value of spare_parts.part_no
     *
     * @mbg.generated
     */
    public String getPartNo() {
        return partNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.part_no
     *
     * @param partNo the value for spare_parts.part_no
     *
     * @mbg.generated
     */
    public void setPartNo(String partNo) {
        this.partNo = partNo == null ? null : partNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.part_name
     *
     * @return the value of spare_parts.part_name
     *
     * @mbg.generated
     */
    public String getPartName() {
        return partName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.part_name
     *
     * @param partName the value for spare_parts.part_name
     *
     * @mbg.generated
     */
    public void setPartName(String partName) {
        this.partName = partName == null ? null : partName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.category
     *
     * @return the value of spare_parts.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.category
     *
     * @param category the value for spare_parts.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.brand
     *
     * @return the value of spare_parts.brand
     *
     * @mbg.generated
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.brand
     *
     * @param brand the value for spare_parts.brand
     *
     * @mbg.generated
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.spec
     *
     * @return the value of spare_parts.spec
     *
     * @mbg.generated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.spec
     *
     * @param spec the value for spare_parts.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.unit
     *
     * @return the value of spare_parts.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.unit
     *
     * @param unit the value for spare_parts.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.cost_price
     *
     * @return the value of spare_parts.cost_price
     *
     * @mbg.generated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.cost_price
     *
     * @param costPrice the value for spare_parts.cost_price
     *
     * @mbg.generated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.sale_price
     *
     * @return the value of spare_parts.sale_price
     *
     * @mbg.generated
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.sale_price
     *
     * @param salePrice the value for spare_parts.sale_price
     *
     * @mbg.generated
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.safety_stock
     *
     * @return the value of spare_parts.safety_stock
     *
     * @mbg.generated
     */
    public Integer getSafetyStock() {
        return safetyStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.safety_stock
     *
     * @param safetyStock the value for spare_parts.safety_stock
     *
     * @mbg.generated
     */
    public void setSafetyStock(Integer safetyStock) {
        this.safetyStock = safetyStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.max_stock
     *
     * @return the value of spare_parts.max_stock
     *
     * @mbg.generated
     */
    public Integer getMaxStock() {
        return maxStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.max_stock
     *
     * @param maxStock the value for spare_parts.max_stock
     *
     * @mbg.generated
     */
    public void setMaxStock(Integer maxStock) {
        this.maxStock = maxStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.location
     *
     * @return the value of spare_parts.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.location
     *
     * @param location the value for spare_parts.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.supplier
     *
     * @return the value of spare_parts.supplier
     *
     * @mbg.generated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.supplier
     *
     * @param supplier the value for spare_parts.supplier
     *
     * @mbg.generated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.is_active
     *
     * @return the value of spare_parts.is_active
     *
     * @mbg.generated
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.is_active
     *
     * @param isActive the value for spare_parts.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.created_time
     *
     * @return the value of spare_parts.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.created_time
     *
     * @param createdTime the value for spare_parts.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.updated_time
     *
     * @return the value of spare_parts.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.updated_time
     *
     * @param updatedTime the value for spare_parts.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spare_parts.remarks
     *
     * @return the value of spare_parts.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spare_parts.remarks
     *
     * @param remarks the value for spare_parts.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}