package com.smartmonkey.model;

import java.math.BigDecimal;
import java.util.Date;

public class StockIn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.in_id
     *
     * @mbg.generated
     */
    private Long inId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.in_no
     *
     * @mbg.generated
     */
    private String inNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.part_id
     *
     * @mbg.generated
     */
    private Long partId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.warehouse
     *
     * @mbg.generated
     */
    private String warehouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.in_type
     *
     * @mbg.generated
     */
    private Byte inType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.unit_price
     *
     * @mbg.generated
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.supplier
     *
     * @mbg.generated
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.in_date
     *
     * @mbg.generated
     */
    private Date inDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.related_order
     *
     * @mbg.generated
     */
    private String relatedOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.in_id
     *
     * @return the value of stock_in.in_id
     *
     * @mbg.generated
     */
    public Long getInId() {
        return inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.in_id
     *
     * @param inId the value for stock_in.in_id
     *
     * @mbg.generated
     */
    public void setInId(Long inId) {
        this.inId = inId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.in_no
     *
     * @return the value of stock_in.in_no
     *
     * @mbg.generated
     */
    public String getInNo() {
        return inNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.in_no
     *
     * @param inNo the value for stock_in.in_no
     *
     * @mbg.generated
     */
    public void setInNo(String inNo) {
        this.inNo = inNo == null ? null : inNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.part_id
     *
     * @return the value of stock_in.part_id
     *
     * @mbg.generated
     */
    public Long getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.part_id
     *
     * @param partId the value for stock_in.part_id
     *
     * @mbg.generated
     */
    public void setPartId(Long partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.warehouse
     *
     * @return the value of stock_in.warehouse
     *
     * @mbg.generated
     */
    public String getWarehouse() {
        return warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.warehouse
     *
     * @param warehouse the value for stock_in.warehouse
     *
     * @mbg.generated
     */
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.in_type
     *
     * @return the value of stock_in.in_type
     *
     * @mbg.generated
     */
    public Byte getInType() {
        return inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.in_type
     *
     * @param inType the value for stock_in.in_type
     *
     * @mbg.generated
     */
    public void setInType(Byte inType) {
        this.inType = inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.quantity
     *
     * @return the value of stock_in.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.quantity
     *
     * @param quantity the value for stock_in.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.unit_price
     *
     * @return the value of stock_in.unit_price
     *
     * @mbg.generated
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.unit_price
     *
     * @param unitPrice the value for stock_in.unit_price
     *
     * @mbg.generated
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.total_amount
     *
     * @return the value of stock_in.total_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.total_amount
     *
     * @param totalAmount the value for stock_in.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.supplier
     *
     * @return the value of stock_in.supplier
     *
     * @mbg.generated
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.supplier
     *
     * @param supplier the value for stock_in.supplier
     *
     * @mbg.generated
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.batch_no
     *
     * @return the value of stock_in.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.batch_no
     *
     * @param batchNo the value for stock_in.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.in_date
     *
     * @return the value of stock_in.in_date
     *
     * @mbg.generated
     */
    public Date getInDate() {
        return inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.in_date
     *
     * @param inDate the value for stock_in.in_date
     *
     * @mbg.generated
     */
    public void setInDate(Date inDate) {
        this.inDate = inDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.operator
     *
     * @return the value of stock_in.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.operator
     *
     * @param operator the value for stock_in.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.related_order
     *
     * @return the value of stock_in.related_order
     *
     * @mbg.generated
     */
    public String getRelatedOrder() {
        return relatedOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.related_order
     *
     * @param relatedOrder the value for stock_in.related_order
     *
     * @mbg.generated
     */
    public void setRelatedOrder(String relatedOrder) {
        this.relatedOrder = relatedOrder == null ? null : relatedOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.created_time
     *
     * @return the value of stock_in.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.created_time
     *
     * @param createdTime the value for stock_in.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.remarks
     *
     * @return the value of stock_in.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.remarks
     *
     * @param remarks the value for stock_in.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}