package com.smartmonkey.model;

import java.util.Date;

public class StockOut {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.out_id
     *
     * @mbg.generated
     */
    private Long outId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.out_no
     *
     * @mbg.generated
     */
    private String outNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.part_id
     *
     * @mbg.generated
     */
    private Long partId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.warehouse
     *
     * @mbg.generated
     */
    private String warehouse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.out_type
     *
     * @mbg.generated
     */
    private Byte outType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.recipient
     *
     * @mbg.generated
     */
    private String recipient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.service_order_no
     *
     * @mbg.generated
     */
    private String serviceOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.out_date
     *
     * @mbg.generated
     */
    private Date outDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.operator
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_out.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.out_id
     *
     * @return the value of stock_out.out_id
     *
     * @mbg.generated
     */
    public Long getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.out_id
     *
     * @param outId the value for stock_out.out_id
     *
     * @mbg.generated
     */
    public void setOutId(Long outId) {
        this.outId = outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.out_no
     *
     * @return the value of stock_out.out_no
     *
     * @mbg.generated
     */
    public String getOutNo() {
        return outNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.out_no
     *
     * @param outNo the value for stock_out.out_no
     *
     * @mbg.generated
     */
    public void setOutNo(String outNo) {
        this.outNo = outNo == null ? null : outNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.part_id
     *
     * @return the value of stock_out.part_id
     *
     * @mbg.generated
     */
    public Long getPartId() {
        return partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.part_id
     *
     * @param partId the value for stock_out.part_id
     *
     * @mbg.generated
     */
    public void setPartId(Long partId) {
        this.partId = partId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.warehouse
     *
     * @return the value of stock_out.warehouse
     *
     * @mbg.generated
     */
    public String getWarehouse() {
        return warehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.warehouse
     *
     * @param warehouse the value for stock_out.warehouse
     *
     * @mbg.generated
     */
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse == null ? null : warehouse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.out_type
     *
     * @return the value of stock_out.out_type
     *
     * @mbg.generated
     */
    public Byte getOutType() {
        return outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.out_type
     *
     * @param outType the value for stock_out.out_type
     *
     * @mbg.generated
     */
    public void setOutType(Byte outType) {
        this.outType = outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.quantity
     *
     * @return the value of stock_out.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.quantity
     *
     * @param quantity the value for stock_out.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.recipient
     *
     * @return the value of stock_out.recipient
     *
     * @mbg.generated
     */
    public String getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.recipient
     *
     * @param recipient the value for stock_out.recipient
     *
     * @mbg.generated
     */
    public void setRecipient(String recipient) {
        this.recipient = recipient == null ? null : recipient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.department
     *
     * @return the value of stock_out.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.department
     *
     * @param department the value for stock_out.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.service_order_no
     *
     * @return the value of stock_out.service_order_no
     *
     * @mbg.generated
     */
    public String getServiceOrderNo() {
        return serviceOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.service_order_no
     *
     * @param serviceOrderNo the value for stock_out.service_order_no
     *
     * @mbg.generated
     */
    public void setServiceOrderNo(String serviceOrderNo) {
        this.serviceOrderNo = serviceOrderNo == null ? null : serviceOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.out_date
     *
     * @return the value of stock_out.out_date
     *
     * @mbg.generated
     */
    public Date getOutDate() {
        return outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.out_date
     *
     * @param outDate the value for stock_out.out_date
     *
     * @mbg.generated
     */
    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.operator
     *
     * @return the value of stock_out.operator
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.operator
     *
     * @param operator the value for stock_out.operator
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.reason
     *
     * @return the value of stock_out.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.reason
     *
     * @param reason the value for stock_out.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.created_time
     *
     * @return the value of stock_out.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.created_time
     *
     * @param createdTime the value for stock_out.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_out.remarks
     *
     * @return the value of stock_out.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_out.remarks
     *
     * @param remarks the value for stock_out.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}